# Generated by Django 5.1.6 on 2025-02-15 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_managers_user_activation_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='activation_code_created',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
