# Generated by Django 5.1.6 on 2025-02-11 16:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SmartContract',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('contract_address', models.CharField(max_length=255, unique=True)),
                ('contract_type', models.CharField(max_length=50)),
                ('abi', models.JSONField()),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TokenTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=8, max_digits=18)),
                ('transaction_type', models.CharField(choices=[('stake', 'Stake'), ('unstake', 'Unstake'), ('payment', 'Payment')], max_length=20)),
                ('blockchain_hash', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserStake',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=8, max_digits=18)),
                ('stake_date', models.DateTimeField(auto_now_add=True)),
                ('unlock_date', models.DateTimeField()),
                ('status', models.CharField(max_length=20)),
            ],
        ),
    ]
